var steamLabActivityList_en = [
  {'title': 'Out of this World Art',
    'desc': '',
    'day':'Thursday',
    'startTime': '10:00 AM',
    'endTime': '10:45 AM'},
  {'title': 'Marbled Shaving Cream Planets',
    'desc': '',
    'day': 'Thursday',
    'startTime': '11:45 AM',
    'endTime': '12:45 PM'},
  {'title': 'Out of this World Art',
  'desc': '',
  'day': 'Thursday',
  'startTime': '1:45 PM',
  'endTime': '2:45 PM'},

  {'title': 'Salt Dough Dinosaur Fossils',
    'desc': '',
    'day':'Friday',
    'startTime': '10:00 AM',
    'endTime': '10:45 AM'},
  {'title': 'Foil Dinosaur Sculptures',
    'desc': '',
    'day': 'Friday',
    'startTime': '11:45 AM',
    'endTime': '12:45 PM'},
  {'title': 'Foil Dinosaur Sculptures',
  'desc': '',
  'day': 'Friday',
  'startTime': '1:45 PM',
  'endTime': '2:45 PM'},

    {'title': 'Bubble Explorations',
      'desc': '',
      'day':'Saturday',
      'startTime': '10:00 AM',
      'endTime': '10:45 AM'},
    {'title': 'Colors of Nature',
      'desc': '',
      'day': 'Saturday',
      'startTime': '11:45 AM',
      'endTime': '12:45 PM'},
    {'title': 'Sunshine Shenanigans',
    'desc': '',
    'day': 'Saturday',
    'startTime': '1:45 PM',
    'endTime': '2:45 PM'},
];

var scienceTheaterActivityList_en = [
  {'title': 'Animals in Our Sky',
    'desc': '',
    'day':'Thursday',
    'startTime': '11:00 AM',
    'endTime': '11:30 AM'},
  {'title': 'Space News',
    'desc': '',
    'day': 'Thursday',
    'startTime': '1:00 PM',
    'endTime': '1:30 PM'},
  {'title': 'Space Artifacts from Collections',
    'desc': '',
    'day': 'Thursday',
    'startTime': '3:00 PM',
    'endTime': '3:30 PM'},

    {'title': 'Dinosaur themed storytime',
      'desc': '',
      'day':'Friday',
      'startTime': '11:00 AM',
      'endTime': '11:30 AM'},
    {'title': 'Dinosaur Ancestors',
      'desc': '',
      'day': 'Friday',
      'startTime': '1:00 PM',
      'endTime': '1:30 PM'},
    {'title': 'Dinosaur Ancestors',
      'desc': '',
      'day': 'Friday',
      'startTime': '3:00 PM',
      'endTime': '3:30 PM'},

    {'title': 'Volts & Jolts: Van de Graaf Generator',
      'desc': '',
      'day':'Saturday',
      'startTime': '11:00 AM',
      'endTime': '11:30 AM'},
    {'title': 'Space News',
      'desc': '',
      'day': 'Saturday',
      'startTime': '1:00 PM',
      'endTime': '1:30 PM'},
    {'title': 'Volts & Jolts: Van de Graaf Generator',
      'desc': '',
      'day': 'Saturday',
      'startTime': '3:00 PM',
      'endTime': '3:30 PM'},
];
