var steamLabActivityList_en = [
  {'title': 'Out of this World Art',
    'desc': 'Stretch your creativity and art skills to make your own planet in an out-of-this-world design challenge.',
    'day':'Thursday',
    'startTime': '10:00 AM',
    'endTime': '10:45 AM'},
  {'title': 'Marbled Shaving Cream Planets',
    'desc': 'Create your own solar system in an out-of-this-world design challenge',
    'day': 'Thursday',
    'startTime': '11:45 AM',
    'endTime': '12:45 PM'},
  {'title': 'Out of this World Art',
  'desc': 'Stretch your creativity and art skills to make your own planet in an out-of-this-world design challenge.',
  'day': 'Thursday',
  'startTime': '1:45 PM',
  'endTime': '2:45 PM'},

  {'title': 'Salt Dough Dinosaur Fossils',
    'desc': 'Flex your paleontology skills as you make your own fossil.',
    'day':'Friday',
    'startTime': '10:00 AM',
    'endTime': '10:45 AM'},
  {'title': 'Foil Dinosaur Sculptures',
    'desc': 'Stretch your imagination and engineering skills through this unique prehistoric STEAM challenge.',
    'day': 'Friday',
    'startTime': '11:45 AM',
    'endTime': '12:45 PM'},
  {'title': 'Foil Dinosaur Sculptures',
  'desc': 'Stretch your imagination and engineering skills through this unique prehistoric STEAM challenge.',
  'day': 'Friday',
  'startTime': '1:45 PM',
  'endTime': '2:45 PM'},

    {'title': 'Bubble Explorations',
      'desc': 'Stretch your imagination and creativity as you explore the wonders of bubbles.',
      'day':'Saturday',
      'startTime': '10:00 AM',
      'endTime': '10:45 AM'},
    {'title': 'Colors of Nature',
      'desc': '',
      'day': 'Saturday',
      'startTime': '11:45 AM',
      'endTime': '12:45 PM'},
    {'title': 'Sunshine Shenanigans',
    'desc': '',
    'day': 'Saturday',
    'startTime': '1:45 PM',
    'endTime': '2:45 PM'},
];

var scienceTheaterActivityList_en = [
  {'title': 'Animals in Our Sky',
    'desc': "Join us as we look closely at some of the animal constellations in our night sky as well as some of the animals in our collection.",
    'day':'Thursday',
    'startTime': '11:00 AM',
    'endTime': '11:30 AM'},
  {'title': 'Space News',
    'desc': 'Catch up on some out-of-this-world excitement with astronomer Dr. Doug Roberts!',
    'day': 'Thursday',
    'startTime': '1:00 PM',
    'endTime': '1:30 PM'},
  {'title': 'Space Artifacts from Collections',
    'desc': 'Join our archivist team for a sneak peek into space through some of the Museum\'s unique space artifacts.',
    'day': 'Thursday',
    'startTime': '3:00 PM',
    'endTime': '3:30 PM'},

    {'title': 'Dinosaur themed storytime',
      'desc': 'Join us for a storytime that will excite your young paleontologist and dinosaur expert.',
      'day':'Friday',
      'startTime': '11:00 AM',
      'endTime': '11:30 AM'},
    {'title': 'Dinosaur Ancestors',
      'desc': 'Join us for an extra special chat with, our Curator of Science, Ms. SpottedBear. She will be discussing some of our resident Dinosaur Ancestors that live at the Museum.',
      'day': 'Friday',
      'startTime': '1:00 PM',
      'endTime': '1:30 PM'},
    {'title': 'Dinosaur Ancestors',
      'desc': 'Join us for an extra special chat with, our Curator of Science, Ms. SpottedBear. She will be discussing some of our resident Dinosaur Ancestors that live at the Museum.',
      'day': 'Friday',
      'startTime': '3:00 PM',
      'endTime': '3:30 PM'},

    {'title': 'Volts & Jolts: Van de Graaf Generator',
      'desc': 'Join us for an electrifying demonstration about the shocking power of electricity!',
      'day':'Saturday',
      'startTime': '11:00 AM',
      'endTime': '11:30 AM'},
    {'title': 'Space News',
      'desc': 'Catch up on some out-of-this-world excitement with astronomer Dr. Doug Roberts!',
      'day': 'Saturday',
      'startTime': '1:00 PM',
      'endTime': '1:30 PM'},
    {'title': 'Volts & Jolts: Van de Graaf Generator',
      'desc': 'Join us for an electrifying demonstration about the shocking power of electricity!',
      'day': 'Saturday',
      'startTime': '3:00 PM',
      'endTime': '3:30 PM'},
];
