var nameDict_en = {
      '1': 'Spacecraft Leak Patch',
      '2': 'Food Preparation Water Gun',
      '3': 'Apollo Spacecraft Heat Shield',
      '4': '<i>Faith 7</i> Heat Shield',
      '5': 'Mylar from Apollo 11',
      '6': 'Lunar Module Data Card',
      '7': 'Fort Worth Flag',
      '8': 'United States Flag',
      '9': 'Apollo Command Module Towels',
      '10': 'Apollo Command Module Window',
      '11': 'Skylab Exercise Bicycle',
      '12': 'Space Shuttle Control Panel',
      '13': 'Space Shuttle Thermal Tile',
      '14': 'Orange Pineapple Drink',
      '15': 'Noodle and Chicken Meal',
      '16': 'Space Shuttle Coveralls',
      '17': "Alan Bean's Apollo Training Suit",
      '18': "Apollo Spacesuit Thermal Garment",
      'error': 'Artifact Not Found!'
    };

var imageDict_en = {
      '1': '',
      '2': 'images/B. Gemini-3-food.jpg',
      '3': 'images/C. Apollo-heat-shield.jpg',
      '4': 'images/D. Mercury-capsule.jpeg',
      '5': 'images/E. A11-on-ship.jpg',
      '6': '',
      '7': '',
      '8': '',
      '9': 'images/I. Schmitt-shaving.jpg',
      '10': 'images/J. Skylab.jpg',
      '11': 'images/K. Conrad-on-bike.jpg',
      '12': 'images/L. Shuttle-flight-deck.jpg',
      '13': 'images/M. Shuttle-Discovery.jpg',
      '14': 'images/N. ISS-coffee.jpg',
      '15': 'images/O. ISS-chopsticks.jpg',
      '16': 'images/P. Sally-Ride.jpg',
      '17': 'images/Q. A12-training.jpg',
      '18': 'images/R. A11-suit.jpg',
      'error': ''
    };

var captionDict_en = {
  '1': '',
  '2': 'The water gun being used to rehydrate food for Gemini 3.',
  '3': "NASA artist's impression of the Command Module returning to Earth.",
  '4': "<i>Faith 7</i> capsule on display at Space Center Houston.",
  '5': 'Apollo 11 Command Module after recovery. Notice the gold Mylar on the outside.',
  '6': '',
  '7': '',
  '8': '',
  '9': 'Apollo 17 astronaut Harrison Schmitt shaving in space.',
  '10': 'Skylab, the first American space station.',
  '11': 'Skylab 2 commander Pete Conrad riding the onboard exercise bike.',
  '12': 'Flight deck on Space Shuttle <i>Endeavor</i>.',
  '13': 'The dark thermal tiles are visible as Space Shuttle <i>Discovery</i> approaches the ISS.',
  '14': 'Italian astronaut Samantha Cristoforetti drinks coffee onboard the ISS.',
  '15': 'Astronaut Sunita Williams using chopsticks while eating dinner in 2007.',
  '16': 'Astronaut Sally Ride wearing coveralls aboard Space Shuttle <i>Challenger</i> in 1983.',
  '17': 'Apollo 12 astronauts Pete Conrad and Alan Bean in their training suits.',
  '18': 'The final equipment used by Neil Armstrong to walk on the Moon.',
  'error': ''
}

var textDict_en = {
      '1': "In the vacuum of space, air is an astronaut's most precious resource. That makes a leak an incredibly serious situation. Spacecraft carried devices like this patch, which could be used to rapidly seal a small puncture. Its bottom is covered in thick glue to form a tight seal. The air pressure inside the capsule would help hold it in place.",
      '2': "Food in space is dried to reduce both its weight and volume. Most food is more than 50% water by weight and even dried fruits like raisins can be nearly a quarter water. Astronauts during the Gemini program rehydrated their food using an onboard water supply. The nozzle you see here would be placed inside a food pouch to release a specified amount of water. Hot water wasn't provided until the Apollo missions, so astronauts during Project Gemini would eat their food cold for up to two weeks at a time!",
      '3': "When the Museum’s curators were selecting items for this exhibition, they almost skipped this one entirely! It's entered into our database not as a piece of heat shield, but as a paperweight, which definitely doesn't sound as interesting. And the catalog is telling the truth—the back of this piece is covered in felt. The heat shield inside comes from AS-201, an uncrewed test flight of the Apollo Command Module. NASA cut pieces from the shield and turned them into gifts for the Apollo astronauts. It's a stark reminder of the thin sheet of material that protected them during a fiery return to Earth.",
      '4': "<i>Faith 7</i> was the sixth and final mission of Project Mercury and carried astronaut Gordon Cooper on 22 orbits of the Earth. Cooper was the first American astronaut to spend more than a day in space. Near the end of his mission, the capsule began experiencing several malfunctions that forced him to initiate a manual landing. This heat shield protected him during that reentry.",
      '5': "Although space is extremely cold, losing heat is actually quite difficult. In a vacuum, the only way to cool down is to wait for your heat to radiate away, a process that is relatively inefficient. Because of that, it's important to keep a spacecraft from getting too warm. Just like here on Earth, a major source of heat in space is light from the Sun. This Mylar was coated the outside of the Apollo 11 Command Module and reflected the Sun's light so that it couldn't warm the capsule. <p> So how did we end up with it? After the Command Module splashed back down on Earth, engineers stripped away pieces of the foil to take home as souvenirs. Two of those pieces eventually ended up in our collection.",
      '6': "Computers during the Space Race were extremely primitive by modern standards. Although the Apollo Command Module and Lunar Module carried a revolutionary minicomputer, many key calculations were made in Mission Control and then relayed by radio to the astronauts. This book provided Apollo 12 astronauts Alan Bean and Pete Conrad with checklists for the lunar landing and a place to note data sent from Earth. You can spot Bean's handwriting on the page—as Lunar Module Pilot, it was his job to relay the information needed by Conrad to land on the Moon.",
      '7': "This Fort Worth flag was carried to the surface of the Moon by Apollo 12 astronaut and Fort Worth Native Alan Bean. NASA allowed each astronaut to carry some personal effects with them on the mission; many used this allowance to carry souvenirs for people and organizations that were important to them. Neil Armstrong established a chapter of a University of Michigan academic fraternity, while the astronauts of Apollo 15 left a memorial to astronauts killed during the Space Race.",
      '8': "Alan Bean carried this US flag to the surface of the Moon in 1969. It wasn't the only one: in addition to the two flags seen here, he also took a Fort Worth flag for the City and a flag from his alma mater, Paschal High School.",
      '9': "In addition to all the specialized equipment needed to explore space, astronauts also needed more ordinary tools. These small towels came standard with the Apollo Command Module and spent two months in space when the capsule served as a lifeboat for the Skylab space station. On trips to the Moon, astronauts used the towels for personal hygiene, such as washing their face or shaving.",
      '10': "Skylab, the first American space station, was built from pats leftover from the Moon program. This window belonged to the Apollo Command Module that carried the crew of Skylab 3 to the station, where it then spent two months in orbit. After it returned to Earth, NASA scientists examined the glass with a microscope and discovered several tiny craters. Each was made by a speck of dust traveling at more than 17,000 miles per hour.",
      '11': "The human body and space just don’t get along. Almost as soon as someone gets into orbit, their body starts breaking down. Their eyesight gets worse, their bones become more brittle, and their muscles begin to weaken. To combat these effects, astronauts on long-duration space missions must exercise obsessively, often for hours a day. On Skylab, a bike exactly like this one was one tool they had at their disposal. What you don't see here is a computer the size of a large suitcase. As astronauts exercised, the computer measured their heartrate, oxygen consumption, and carbon dioxide production. These data were transmitted to doctors on the ground. This information informed scientists as they prepared for astronauts to spend months or even a year aboard the International Space Station.",
      '12': "Although the flight deck of the Space Shuttle contained nine digital displays, nearly all of its controls were mechanical switches like the ones you see here. Notice the metal ring on either side of the switch. These served two purposes. One was to reduce the likelihood of accidently flipping the switch by bumping into it. The other was to provide a place to hook a finger while using the controls. This helped keep an astronaut from floating away as they worked the controls. You'll notice similar switch guards on the Skylab exercise bike to your left.",
      '13': "The thermal tiles were an important innovation on the Space Shuttle, but also a source of recurring trouble. From the beginning, the Shuttle was designed for frequent trips to space, with NASA at one point estimating there could be more than 25 launches a year. The thermal tiles were designed to replace traditional heat shields, like the ones on display on the wall behind you. Instead of frequently replacing a single, bulky shield, individual tiles could be replaced as they became damaged.<p>Unfortunately, while extremely resistant to heat, the tiles were quite fragile and needed frequent replacement. And in 2003, a tile was knocked off during launch by a piece of ice, causing the destruction of Space Shuttle <i>Columbia</i> and the loss of its crew.",
      '14': "Just like here on Earth, hydration is key to maintaining good health for astronauts. And good hydration is more than just water—it's important to get enough electrolytes, or salts, with your beverages. Early astronauts were simply given pure water and tablets of salt, but they often used in the wrong ratio. Modern space beverages, like this orange pineapple drink, can be both healthy and tasty, ensuring astronauts stay well-hydrated.",
      '15': "The food on early space missions was simply terrible. Typical meals would involve combinations of dehydrated cubes and pastes that, while nutritious, barely qualified as food. Many astronauts found the meals so unpalatable that they would simply not eat or eat as little as possible. That approach is not sustainable now that we're sending people into space for months at a time, so modern space food has been dramatically improved. Astronauts on the International Space Station can choose from dozens of different meals, including multicultural staples like kimchi.",
      '16': "Coveralls like these were worn by astronauts on early Shuttle missions during the launch and reentry phases. Because the Space Shuttle was supposed to represent a new, safer era of space flight, NASA didn't require the bulky pressure suits worn by astronauts during the Space Race. That all changed after 1986 <i>Challenger</i> accident, which resulted in the loss of the crew.",
      '17': "Of the twelve men who walked on the Moon, only one was a scientist. The rest received extensive scientific training, especially in geology. Apollo 12 astronaut Alan Bean wore this suit while completing mission training activities in the desert. The astronauts practiced identifying and collecting rock samples, deploying experiments, and simply maneuvering in their bulky suits.",
      '18': "The first spacewalking astronauts all encountered the same problem: heat. Although space can be very cold, spacesuits trap heat effectively. On early spacewalks, astronauts sweated so much that their helmets fogged up and some even became dangerously overheated. NASA knew that Moonwalkers couldn't afford these problems, so they developed methods for keeping astronauts cool in their suit.<p>This prototype garment conducts heat efficiently, making it extremely cold to the touch even today. It was produced in 1965 for Edgar Mitchell, who eventually walked on the Moon as part of Apollo 14. But when he did, he wasn't wearing this. By then, NASA had settled on a design that circulated cool water through the suit and enabled each astronaut to set their preferred temperature.",
      'error': "Oops, an artifact with that number does't seem to exist in this gallery. Please double check that you've selected the appropriate gallery and then try a different number!"
    };

var audioDict_en = {
  '1': 'audio/en/A. Leak Patch.mp3',
  '2': 'audio/en/B. Water Gun.mp3',
  '3': 'audio/en/C. Apollo Heat Shield.mp3',
  '4': 'audio/en/D. Faith 7 Heat Sheild.mp3',
  '5': 'audio/en/E. Mylar.mp3',
  '6': 'audio/en/F. LM Data Card.mp3',
  '7': 'audio/en/G. Fort Worth Flag.mp3',
  '8': 'audio/en/H. US Flag.mp3',
  '9': 'audio/en/I. Towels.mp3',
  '10': 'audio/en/J. Window.mp3',
  '11': 'audio/en/K. Skylab Bike.mp3',
  '12': 'audio/en/L. Shuttle control panel.mp3',
  '13': 'audio/en/M. Shuttle Tile.mp3',
  '14': 'audio/en/N. Pineapple Drink.mp3',
  '15': 'audio/en/O. Chicken Meal.mp3',
  '16': 'audio/en/P. Shuttle Coveralls.mp3',
  '17': 'audio/en/Q. Bean Suit.mp3',
  '18': 'audio/en/R. Prototype suit.mp3'
}

var nameDict_es = {
      '1': 'Parche de fugas de naves espaciales',
      '2': 'Preparación de alimentos pistola de agua',
      '3': 'Escudo de calor de la nave espacial Apollo',
      '4': '<i>Faith 7</i> Escudo térmico',
      '5': 'Mylar del Apollo 11',
      '6': 'Tarjeta de datos del módulo lunar',
      '7': 'Bandera de Fort Worth',
      '8': 'Bandera de estados unidos',
      '9': 'Toallas del módulo de comando Apollo',
      '10': 'Ventana del módulo de comando Apollo',
      '11': 'Bicicleta de ejercicio Skylab',
      '12': 'Panel de control del transbordador espacial',
      '13': 'Transbordador espacial baldosas térmicas',
      '14': 'Bebida De Piña Y Naranja',
      '15': 'Comida de fideos y pollo',
      '16': 'Overol de transbordador espacial',
      '17': "Traje de entrenamiento Apollo de Alan Bean",
      '18': "Traje térmico de traje espacial Apollo",
      'error': '¡Artefacto no encontrado!'
    };

var imageDict_es = {
      '1': '',
      '2': 'images/B. Gemini-3-food.jpg',
      '3': 'images/C. Apollo-heat-shield.jpg',
      '4': 'images/D. Mercury-capsule.jpeg',
      '5': 'images/E. A11-on-ship.jpg',
      '6': '',
      '7': '',
      '8': '',
      '9': 'images/I. Schmitt-shaving.jpg',
      '10': 'images/J. Skylab.jpg',
      '11': 'images/K. Conrad-on-bike.jpg',
      '12': 'images/L. Shuttle-flight-deck.jpg',
      '13': 'images/M. Shuttle-Discovery.jpg',
      '14': 'images/N. ISS-coffee.jpg',
      '15': 'images/O. ISS-chopsticks.jpg',
      '16': 'images/P. Sally-Ride.jpg',
      '17': 'images/Q. A12-training.jpg',
      '18': 'images/R. A11-suit.jpg',
      'error': ''
    };

var captionDict_es = {
  '1': '',
  '2': 'La pistola de agua que se usa para rehidratar alimentos para Géminis 3.',
  '3': "Impresión artística de la NASA del Módulo de Comando que regresa a la Tierra.",
  '4': "<i>Faith 7</i> cápsula en exhibición en el Centro Espacial de Houston.",
  '5': 'Módulo de comando Apollo 11 después de la recuperación. Observe el oro Mylar en el exterior.',
  '6': '',
  '7': '',
  '8': '',
  '9': 'El astronauta del Apolo 17 Harrison Schmitt se afeita en el espacio.',
  '10': 'Skylab, la primera estación espacial estadounidense.',
  '11': 'El comandante de Skylab 2, Pete Conrad, monta la bicicleta estática a bordo.',
  '12': 'Cubierta de vuelo en el transbordador espacial <i>Endeavor</i>.',
  '13': 'Las baldosas térmicas oscuras son visibles cuando el transbordador espacial <i>Discovery</i> se acerca a la ISS.',
  '14': 'La astronauta italiana Samantha Cristoforetti toma café a bordo de la EEI.',
  '15': 'La astronauta Sunita Williams usando palillos mientras cenaba en 2007.',
  '16': 'La astronauta Sally Ride con overol a bordo del transbordador espacial <i>Challenger</i> en 1983.',
  '17': 'Los astronautas del Apollo 12 Pete Conrad y Alan Bean en sus trajes de entrenamiento.',
  '18': 'El equipo final utilizado por Neil Armstrong para caminar sobre la Luna.',
  'error': ''
}

var textDict_es = {
      '1': "En el vacío del espacio, el aire es el recurso más preciado de un astronauta. Eso hace que una fuga sea una situación increíblemente grave. La nave espacial transportaba dispositivos como este parche, que podrían usarse para sellar rápidamente un pequeño pinchazo. Su parte inferior está cubierta de pegamento grueso para formar un sello hermético. La presión del aire dentro de la cápsula ayudaría a mantenerla en su lugar.",
      '2': "Los alimentos en el espacio se secan para reducir tanto su peso como su volumen. La mayoría de los alimentos contienen más del 50% de agua en peso e incluso las frutas secas como las pasas pueden ser casi un cuarto de agua. Los astronautas durante el programa Gemini rehidrataron sus alimentos utilizando un suministro de agua a bordo. La boquilla que ve aquí se colocaría dentro de una bolsa de comida para liberar una cantidad específica de agua. ¡No se proporcionó agua caliente hasta las misiones Apollo, por lo que los astronautas durante el Proyecto Géminis comerían su comida fría por hasta dos semanas a la vez!",
      '3': "Cuando los curadores del museo estaban seleccionando elementos para esta exposición, ¡casi se saltaron esta por completo! Se ingresó en nuestra base de datos no como un escudo térmico, sino como un pisapapeles, que definitivamente no suena tan interesante. Y el catálogo dice la verdad: la parte posterior de esta pieza está cubierta de fieltro. El escudo térmico en el interior proviene de AS-201, un vuelo de prueba sin tripulación del Módulo de Comando Apollo. La NASA cortó piezas del escudo y las convirtió en regalos para los astronautas del Apollo. Es un claro recordatorio de la delgada lámina de material que los protegió durante un ardiente regreso a la Tierra.",
      '4': "<i>Faith 7</i> fue la sexta y última misión del Proyecto Mercurio y transportó al astronauta Gordon Cooper en 22 órbitas de la Tierra. Cooper fue el primer astronauta estadounidense en pasar más de un día en el espacio. Cerca del final de su misión, la cápsula comenzó a experimentar varios fallos de funcionamiento que lo obligaron a iniciar un aterrizaje manual. Este escudo térmico lo protegió durante esa reentrada.",
      '5': "Aunque el espacio es extremadamente frío, perder calor es bastante difícil. En el vacío, la única forma de enfriarse es esperar a que su calor se irradie, un proceso que es relativamente ineficiente. Por eso, es importante evitar que una nave espacial se caliente demasiado. Al igual que aquí en la Tierra, una fuente importante de calor en el espacio es la luz del Sol. Este Mylar estaba cubierto por el exterior del Módulo de Comando Apolo 11 y reflejaba la luz del Sol para que no pudiera calentar la cápsula.<p>Entonces, ¿cómo terminamos con eso? Después de que el Módulo de Comando volviera a caer sobre la Tierra, los ingenieros quitaron pedazos de la lámina para llevarlos a casa como recuerdos. Dos de esas piezas finalmente terminaron en nuestra colección.",
      '6': "Las computadoras durante la carrera espacial fueron extremadamente primitivas para los estándares modernos. Aunque el Módulo de Comando Apollo y el Módulo Lunar llevaban una minicomputadora revolucionaria, muchos cálculos clave se realizaron en Control de Misión y luego se transmitieron por radio a los astronautas. Este libro proporcionó a los astronautas del Apollo 12 Alan Bean y Pete Conrad listas de verificación para el aterrizaje lunar y un lugar para anotar los datos enviados desde la Tierra. Puedes ver la letra de Bean en la página. Como piloto del módulo lunar, era su trabajo transmitir la información que Conrad necesitaba para aterrizar en la Luna.",
      '7': "Esta bandera de Fort Worth fue llevada a la superficie de la Luna por el astronauta del Apollo 12 y Alan Bean, nativo de Fort Worth. La NASA permitió que cada astronauta llevara consigo algunos efectos personales en la misión; muchos utilizaron esta asignación para llevar recuerdos para personas y organizaciones que eran importantes para ellos. Neil Armstrong estableció un capítulo de una fraternidad académica de la Universidad de Michigan, mientras que los astronautas del Apollo 15 dejaron un monumento a los astronautas asesinados durante la Carrera Espacial.",
      '8': "Alan Bean llevó esta bandera estadounidense a la superficie de la Luna en 1969. No fue la única: además de las dos banderas que se ven aquí, también tomó una bandera de Fort Worth para la Ciudad y una bandera de su alma mater, Escuela secundaria Paschal.",
      '9': "Además de todo el equipo especializado necesario para explorar el espacio, los astronautas también necesitaban herramientas más comunes. Estas pequeñas toallas vienen de serie con el módulo de comando Apollo y pasaron dos meses en el espacio cuando la cápsula sirvió como bote salvavidas para la estación espacial Skylab. En los viajes a la Luna, los astronautas usaban las toallas para la higiene personal, como lavarse la cara o afeitarse.",
      '10': "Skylab, la primera estación espacial estadounidense, se construyó a partir de los restos del programa Moon. Esta ventana pertenecía al Módulo de Comando Apollo que llevó a la tripulación del Skylab 3 a la estación, donde luego pasó dos meses en órbita. Después de que regresó a la Tierra, los científicos de la NASA examinaron el vidrio con un microscopio y descubrieron varios pequeños cráteres. Cada uno fue hecho por una mota de polvo que viajaba a más de 17,000 millas por hora.",
      '11': "El cuerpo humano y el espacio simplemente no se llevan bien. Casi tan pronto como alguien entra en órbita, su cuerpo comienza a descomponerse. Su vista empeora, sus huesos se vuelven más frágiles y sus músculos comienzan a debilitarse. Para combatir estos efectos, los astronautas en misiones espaciales de larga duración deben hacer ejercicio obsesivamente, a menudo durante horas al día. En Skylab, una bicicleta exactamente como esta era una herramienta que tenían a su disposición. Lo que no ves aquí es una computadora del tamaño de una maleta grande. Mientras los astronautas hacían ejercicio, la computadora midió su frecuencia cardíaca, consumo de oxígeno y producción de dióxido de carbono. Estos datos fueron transmitidos a los médicos en el terreno. Esta información informó a los científicos mientras se preparaban para que los astronautas pasaran meses o incluso un año a bordo de la Estación Espacial Internacional.",
      '12': "Aunque la cubierta de vuelo del transbordador espacial contenía nueve pantallas digitales, casi todos sus controles eran interruptores mecánicos como los que se ven aquí. Observe el anillo de metal a cada lado del interruptor. Estos sirvieron para dos propósitos. Una era reducir la probabilidad de activar accidentalmente el interruptor tropezando con él. El otro era proporcionar un lugar para enganchar un dedo mientras se usan los controles. Esto ayudó a evitar que un astronauta se alejara flotando mientras trabajaban los controles. Notará protectores de interruptor similares en la bicicleta de ejercicios Skylab a su izquierda.",
      '13': "Las baldosas térmicas fueron una innovación importante en el transbordador espacial, pero también una fuente de problemas recurrentes. Desde el principio, el Shuttle fue diseñado para viajes frecuentes al espacio, y la NASA en un momento estimó que podría haber más de 25 lanzamientos al año. Las baldosas térmicas fueron diseñadas para reemplazar los escudos térmicos tradicionales, como los que se muestran en la pared detrás de usted. En lugar de reemplazar con frecuencia un solo escudo voluminoso, las fichas individuales podrían reemplazarse a medida que se dañaran.<p>Desafortunadamente, aunque extremadamente resistentes al calor, las fichas eran bastante frágiles y necesitaban un reemplazo frecuente. Y en 2003, un azulejo fue derribado durante el lanzamiento por un trozo de hielo, causando la destrucción del transbordador espacial <i>Columbia</i> y la pérdida de su tripulación.",
      '14': "Al igual que aquí en la Tierra, la hidratación es clave para mantener una buena salud para los astronautas. Y una buena hidratación es más que solo agua: es importante obtener suficientes electrolitos o sales con sus bebidas. Los primeros astronautas simplemente recibieron agua pura y tabletas de sal, pero a menudo se usaron en una proporción incorrecta. Las bebidas espaciales modernas, como esta bebida de naranja y piña, pueden ser saludables y sabrosas, asegurando que los astronautas se mantengan bien hidratados.",
      '15': "La comida en las primeras misiones espaciales fue simplemente terrible. Las comidas típicas implicarían combinaciones de cubos deshidratados y pastas que, aunque nutritivas, apenas califican como alimento. Muchos astronautas encontraron las comidas tan desagradables que simplemente no comerían o comerían lo menos posible. Ese enfoque no es sostenible ahora que estamos enviando personas al espacio durante meses, por lo que la comida espacial moderna se ha mejorado drásticamente. Los astronautas de la Estación Espacial Internacional pueden elegir entre docenas de comidas diferentes, incluidos alimentos básicos multiculturales como el kimchi.",
      '16': "Overoles como estos fueron usados ​​por los astronautas en las primeras misiones de Shuttle durante las fases de lanzamiento y reentrada. Debido a que se suponía que el transbordador espacial representaría una nueva era más segura de los vuelos espaciales, la NASA no requirió los trajes de presión voluminosos que usaron los astronautas durante la carrera espacial. Todo eso cambió después del accidente de <i>Challenger</i> de 1986, que resultó en la pérdida de la tripulación.",
      '17': "De los doce hombres que caminaron en la Luna, solo uno era científico. El resto recibió una amplia formación científica, especialmente en geología. El astronauta del Apollo 12, Alan Bean, usó este traje mientras completaba actividades de entrenamiento de misión en el desierto. Los astronautas practicaban identificar y recolectar muestras de rocas, desplegar experimentos y simplemente maniobrar con sus voluminosos trajes.",
      '18': "Los primeros astronautas de la caminata espacial encontraron el mismo problema: el calor. Aunque el espacio puede ser muy frío, los trajes espaciales atrapan el calor de manera efectiva. En las primeras caminatas espaciales, los astronautas sudaban tanto que sus cascos se empañaron y algunos incluso se sobrecalentaron peligrosamente. La NASA sabía que los Moonwalkers no podían permitirse estos problemas, por lo que desarrollaron métodos para mantener a los astronautas frescos con su traje. Fue producido en 1965 para Edgar Mitchell, quien finalmente caminó en la Luna como parte del Apollo 14. Pero cuando lo hizo, no estaba usando esto. Para entonces, la NASA se había decidido por un diseño que hacía circular agua fría a través del traje y permitía a cada astronauta establecer su temperatura preferida.",
      'error': "Vaya, un artefacto con ese número no parece existir en esta galería. ¡Verifique que haya seleccionado la galería apropiada y luego intente con un número diferente!"
    };

var audioDict_es = {
  '1': 'space-1.mp3',
  '2': 'space-2.mp3',
  '3': 'space-3.mp3',
}
