var use_keypad_entry = true;

var title_en = 'Beads';
var title_es = "Beads";

var nameDict_en = {
      '1': 'Clay Bisque Beads',
      "2": "Prehistoric Culture Beads",
      "3": "Ostrich Feather Headdress",
      "4": "Beaded Dress",
      "5": "Goat Hair Necklace",
      "6": "Blue Faience Necklace",
      "7": "Amulet Necklace",
      "8": "Moche Necklace",
      "9": "Jade Celt Pendant",
      "10": "Ojibwa Beaded Bandolier",
      "11": "Cree “Octopus” Beaded Pouch",
      "12": "Comanche Saddle Blanket",
      "13": "Cheyenne Knife Sheath",
      "14": "Trade Beads",
      "15": "Woodland Bag",
      "16": "Victorian Beaded Purse",
      "17": "Women’s Beaded Boots",
      "18": "Ida Loving Turner's Gown",
      "19": "Prussian Beaded Purse",
      "20": "Eagle Claw Necklace",
      "21": "Deerskin Shirt",
      "22": "Beaded Vest",
      "23": "Beaded Moccasins",
      "24": "Wood and Beaded Necklaces",
      "25": "Beaded Bracelet",
      "26": "Ostrich Egg Necklace",
      'error': 'Artifact Not Found!'
    };

var imageDict_en = {
      '1': 'images/Mohenjo-daro.jpg',
      '2': 'images/Spiro_Craig_Mound_HRoe.jpg',
      '3': 'images/Massai_warriors.jpg',
      '4': 'images/Londons_Carnaby_Street,_1966.jpg',
      '5': '',
      '6': 'images/Egyptian_faience_beads.jpg',
      '7': 'images/Eye_of-Horus.png',
      '8': 'images/Moche_bat.jpg',
      '9': 'images/Jadestein.jpg',
      '10': 'images/Hombres_ojibwe.jpg',
      '11': 'images/Cree.jpg',
      '12': 'images/Comanche.jpg',
      '13': '',
      '14': '',
      '15': '',
      '16': 'images/Frith_A_Private_View_detail.jpg',
      '17': 'images/Frith_A_Private_View_detail.jpg',
      '18': 'images/Turner_photo.jpg',
      '19': 'images/Frith_A_Private_View_detail.jpg',
      '20': 'images/Bald_Eagle.jpg',
      '21': 'images/Tanning.jpg',
      '22': '',
      '23': '',
      '24': '',
      '25': '',
      '26': 'images/ostrich_egg.jpg',
      'error': ''
}

var captionDict_en = {
      '1': 'Excavated ruins of Mahenjo daro, a city that was once part of the Indus Valley Civilization. (Image credit: Saqib Qayyum)',
      '2': 'A large burial mound found as part of the Spiro Mounds in Oklahoma. (Image credit: Herb Roe)',
      '3': 'Maasai warriors as seen by a German photographer in the early 1900s. (Image credit: Walther Dobbertin)',
      '4': 'Friends gather in London in 1965.',
      '5': '',
      '6': 'A collection of Egyptian faience beads for use during funerals. (Image credit: Nsingapuri)',
      '7': 'The Eye of Horus symbol. (Image credit: User eff Dahl)',
      '8': 'This crescent-shaped Moche ornament depicts a bat. Animals feature heavily in Moche art.',
      '9': 'The appearance of natural jade.',
      '10': 'Five Ojibwe chiefs in the 19th century.',
      '11': 'A Cree group in the early 1900s.',
      '12': 'A Comanche warrior and his horse in the late 1800s.',
      '13': '',
      '14': '',
      '15': '',
      '16': "This 1883 painting shows the variety of late Victorian women's fashion.",
      '17': "This 1883 painting shows the variety of late Victorian women's fashion.",
      '18': 'Ida Loving Turner (left) and her daughter, Alma Turner Phelps (right).',
      '19': "This 1883 painting shows the variety of late Victorian women's fashion.",
      '20': 'A bald eagle in flight. (Image credit: Peter K Burian)',
      '21': 'A Native American woman, seen left, tans a hide in 1932.',
      '22': '',
      '23': '',
      '24': '',
      '25': '',
      '26': 'Ostrich eggs in their nest.',
      'error': ''
}


var textDict_en = {
      '1': "These beads are some of the oldest examples of beadmaking we have in our collection. The beads were found at the archaeological site of Lothal in present-day northwest India. Lothal was a port-city during the Bronze Age. It is an example of the Indus Valley Culture, also referred to as a Harappan culture. The metropolis flourished along the river basin with the city being organized into an upper and lower town. The upper town was where the bath house, granaries, municipal and religious buildings were located, while the lower town was where the majority of people lived and worked. There is evidence at the Lothal site of a beadmaking worksite in the lower town area.",
      '2': 'These beads were found at an archaeological site outside Spiro, Oklahoma. This prehistoric settlement became permanent around 800 CE and is considered part of the Mississippian Period. The site boasts around twelve mounds, with evidence of a large trade network and political or religious center. These are all characteristics of a "Mound Builders" culture that existed for about 5,000 years in North America, in which peoples built large earthen mounds to serve various purposes. ',
      '3': "The Maasai people reside in parts of present-day Kenya and Tanzania. This semi-nomadic culture rely on their livestock of cattle, goats, and sheep for food and trade. Their beadwork is centered on women of all ages and is passed down from mother to daughter. For this headdress, a warrior would participate in a rite of passage involving lion hunting. Should the warrior prove successful, a similar headdress would then be created by women of the community and given to him in celebration of his bravery.",
      '4': "The 1960s brought in new styles for American women's clothing. Differing from longer and fuller skirts and dresses, the new styles focused on more form-fitting garments with shorter hemlines. Sheath dresses became very popular due to their fitting slightly looser (but still considered a narrower cut) and how comfortable they were for movement. This new, easy-to-wear style could be accessorized with belts, various jewelry, boots and heels. Fabric was also changing to incorporate more colors and patterns and with just enough tailoring to emphasize women's curves. Beading at this time was added for both style and status.",
      '5': 'Also referred to as a collar, this piece is an example of traditional regalia worn by a prominent man of the Bakuba tribe. The Bakuba or Kuba is a tribe located in the Democratic Republic of Congo. The Kuba Kingdom is made up of around 18 groups, all of which are considered part of the Bantu language-speaking peoples. The Bakuba are farmers, but also hunt and fish. The tribes are known for their elaborate masks and raffia textiles. A king, who is held responsible by a courts council, represents the form of government for the Kuba tribe.',
      '6': "Egyptian faience refers to a ceramic with a bright colored glaze. The blue color was very popular to ancient Egyptians; the color is linked to fertility and life. Faience can be seen in an array of objects, with beads being some of the earliest produced. According to scholars, it is most likely either Egypt or the Near East where faience was originally invented, roughly 6000 years ago. Jewelry was worn by both men and women during ancient Egyptian times, regardless of differing social classes. Ancient Egyptians also placed emphasis on their deceased wearing jewelry in preparation for the afterlife.",
      '7': "Jewelry was important to ancient Egyptians. They wore it on a daily basis and often one of their necklaces would have an amulet attached to it. Amulets, or pendants, had symbolic meaning and were believed to magically bestow positive properties or offer protection to the wearer. They would be made out of various materials and could represent different meanings. Amulets would adorn the deceased and protect them in the next life.",
      '8': "The Moche civilization, also known as Mochica, existed from about 100 CE – 800 BCE along the coast of present-day Peru. The civilization was known for their art and architecture. The reason behind the collapse of Moche culture is still unknown. The civilization was known for beautifully-painted friezes and murals along the walls of their various complexes and possible palaces.",
      '9': "This beautiful necklace is made of large jade stones. Jadeite was highly prized throughout Mesoamerican and upper South American cultures. Jadeite is an aluminum and sodium silicate and the only known area from which it was sourced is in Guatemala. Archaeologists still debate other possible locations in Mesoamerica. In addition to jade, there were also other greenstones such as quartz or serpentine that were not as rare, but a preferred alternative.",
      '10': "The Ojibwa tribe, also referred to as the Chippewa, are an Algonquian-speaking nation who live in the Great Lakes region of the United States, as well as parts of Ontario, Canada. Some of the first experiences the Ojibwa had with Europeans were with those interested in establishing a fur trade with them. These straps have a common floral motif that is also seen on other items Ojibwa women create.",
      '11': "This style of pouch has an interesting story on how it came to be known as an octopus bag. These bags were originally made of animal skins, often keeping the tail and head of the animal along with additional beadwork. Over time these animal bags found their way to the Northwest coast, taking on tentacle-like features and a dome-shape. Northwest tribes noted the similarities between these bags and octopus, hence the name.",
      '12': "The Comanche were known for their horsemanship. Horses became a central component in their culture. They aided the Comanche when moving through most of the southern plains of the United States and into northern Mexico. They both fought and hunted on horseback, along with breeding herds to increase their wealth. These animals were highly prized and often a focal point when raiding.  ",
      '13': "Both the saddle blanket and the knife sheath in this case represent the lazy stitch, or lane stitch, technique of bead working. The leather they used was tanned by holding the hide under running water and then scrapping all the hair off the hide. They then rubbed a brain and liver paste over the hide and vigorously scrubbed it to make the leather soft. In fact, the leather gets so soft that the beading needle can be retracted through the hide after a stitch has been made if the artist does not like how the stitch or beads are laying on the piece. Aside from the first and last stitch, the stitching will also not be seen from the back of the leather as the stitch is just barely piercing the top of the hide.",
      '14': 'These trade beads are made of white ceramic. Many Native American tribes used beads as a status symbol, a form of currency, or to aid in settling disputes. A well-known example of trade beads are the “wampum” made from marine shell. The wampum beads would be strung together and served several important purposes, especially amongst the northeastern tribes of the United States.',
      '15': "Woodland Tribe bandolier bags were made almost exclusively by women. In the late 19th century, they were sometimes traded with Plains tribes in exchange for horses. These bags could take upwards of a year to make. The bags were often designed to be worn by men during ceremonial dances. The type of stitching used in this piece is called a two-needle applique technique, wherein a long line of beads will be laid on the leather or fabric and then stitched down periodically to form the more curvilinear lines that are found in florals and other non-geometric patterns. The stitching in this technique will be seen on the back of the leather or fabric, unlike the lazy or lane stitching technique.",
      '16': 'The beaded shoes and handbags in this case are a good example of beadwork going glam. These Victorian-era pieces were made for show. They demonstrated a certain higher level of socio-economic status of the time. Victorians were keen to keep themselves busy, so beadwork flourished and became more elaborate. The kinds of beaded items from this era are vast, including pen holders, scissor holders, hand-held fans, vases, pin cushions, tea cozies, collars and cuffs, sofa cushions, chairs and candlesticks.',
      '17': "The beaded shoes and handbags in this case are a good example of beadwork going glam. These Victorian-era pieces were made for show. They demonstrated a certain higher level of socio-economic status of the time. Victorians were keen to keep themselves busy, so beadwork flourished and became more elaborate. The kinds of beaded items from this era are vast, including pen holders, scissor holders, hand-held fans, vases, pin cushions, tea cozies, collars and cuffs, sofa cushions, chairs and candlesticks.",
      '18': "Ida Loving Turner is a fairly unknown Fort Worth philanthropist. She does not get nearly the recognition she deserves. Ida was a member of the Texas chapter of Lady Managers. She was Fort Worth’s second postmistress; held a role in decorating the Spring Palace; was involved in the humane society; and was the spark that began what is now Cook Children’s Hospital. Ida also sold some of her land to the City that is now part of Forest Park. One of her buildings, The Alma Building, named after her daughter, can still be seen on Forest Park Boulevard today. The Alma Building used to be Tillery’s Market, but now serves as an office space building. The gown you are looking at today was worn by Ida Loving Turner at the 1893 Chicago World’s Fair and was designed for her by The House of Worth in Paris, France. The House of Worth has no relation to Fort Worth, but was one of the leading fashion houses of the time. The dress was donated to the Museum by the family of Ida Loving Turner.",
      '19': "The beaded shoes and handbags in this case are a good example of beadwork going glam. These Victorian-era pieces were made for show. They demonstrated a certain higher level of socio-economic status of the time. Victorians were keen to keep themselves busy, so beadwork flourished and became more elaborate. The kinds of beaded items from this era are vast, including pen holders, scissor holders, hand-held fans, vases, pin cushions, tea cozies, collars and cuffs, sofa cushions, chairs and candlesticks.",
      '20': "Some Native Americans hold a belief that eagles are closer to God than are humans. Similar beliefs are mirrored in many cultures across the globe, linking cultures in honor to similar materials without ever physically connecting—including a recent discovery that Neanderthals used eagle talons for decorative purposes. Today federally-recognized Native American tribes can obtain eagle talons and/or feathers for their use via permit through the U.S. Fish and Wildlife Service.",
      '21': "Early Plains beadwork consisted mostly of irregularly-shaped beads, quillwork and simple geometric patterns that used only a few basic patterns. Individual tribes could be identified by the color and design preference of their beadwork. The fur trade enabled the Plains Indians a freedom to acquire more material goods, including glass beads introduced by Europeans. Designs became more distinct, but simple geometric patterns remained. Regional styles developed further distinguishing tribal affiliations. While we do not know which tribe created this shirt, it is a beautiful example of the Plains Indian beading craftsmanship and European influence.",
      '22': "Forced relocations and life on the reservation left tribal members with time on their hands, leading to a proliferation of beadwork during the mid-nineteenth century. Italian and Czech beads were often used in Native American bead working, with beads from Czechoslovakia perhaps favored for their uniformity. While we do not know where the beads came from on this vest, it is most likely that they came from a European source. Both European and Asian bead makers traded their beads across the globe, indicating a common thread of cultural affection for beads and their limitless potential.",
      '23': "The Athabascan people were beading long before Europeans introduced beads to the culture. They used shells, natural stone, and porcupine quills for beads. They used flint to bore holes in their natural beads. The Athabascan were nomadic. A travelling group would develop their own patterns and color preferences along their journey. While glass beads were certainly introduced by Europeans, they usually made their way into roaming Athabascan groups via other Athabascans groups. Designs are often rooted in the deeply spiritual connection Athabascans hold with the animal kingdom, as seen on these moccasins.",
      '24': "Africans created a range of natural beads in their artwork for centuries before glass beads arrived on the scene. There is a very complex narrative about how glass beads made their way to Africa, with differing opinions and a focus on the study of the chemical makeup of archeological beads to try and determine their origins. Some believe that the earliest beads arrived from India. We know that Africa also traded with Europeans for glass beads in medieval times. It is also known that Sub-Saharan Africa, Egypt, and Northern Africa all have varying degrees of history surrounding the arrival of glass beads to their respective regions. There is archeological evidence that glassmaking was already in practice in Africa before Arab, Indian and European cultures arrived with their wares. In any case, Africa has embraced glass bead working for centuries as seen in these simple but elegant necklaces and bracelet.",
      '25': "Africans created a range of natural beads in their artwork for centuries before glass beads arrived on the scene. There is a very complex narrative about how glass beads made their way to Africa, with differing opinions and a focus on the study of the chemical makeup of archeological beads to try and determine their origins. Some believe that the earliest beads arrived from India. We know that Africa also traded with Europeans for glass beads in medieval times. It is also known that Sub-Saharan Africa, Egypt, and Northern Africa all have varying degrees of history surrounding the arrival of glass beads to their respective regions. There is archeological evidence that glassmaking was already in practice in Africa before Arab, Indian and European cultures arrived with their wares. In any case, Africa has embraced glass bead working for centuries as seen in these simple but elegant necklaces and bracelet.",
      '26': "Ostrich egg beads have a very long history. In fact, researchers are discovering dynamic human networking relations dating as far back as the late Middle Stone Age by isotope analysis of ostrich egg beads. Ostrich egg beads can also help date an archeological site and researchers are learning how humanity dealt with issues such as outside cultural contact, economic shifts and climate change based on these dynamic and ancient little beads. Unassuming yet elegant, ostrich egg beads are packed with historical significance.",
      'error': "Oops, an artifact with that number does't seem to exist in this gallery. Please double check that you've selected the appropriate gallery and then try a different number!"
    };

var audioDict_en = {
      '1': 'audio/en/A-indus_valley.mp3',
      '2': 'audio/en/B-spiro_mound.mp3',
      '3': 'audio/en/C-massai-headdress.mp3',
      '4': 'audio/en/D-1968-dress.mp3',
      '5': 'audio/en/E-goat-hair-necklace.mp3',
      '6': 'audio/en/F-faience.mp3',
      '7': 'audio/en/G-egyptian-amulet.mp3',
      '8': 'audio/en/H-Moche-necklace.mp3',
      '9': 'audio/en/I-jade-necklace.mp3',
      '10': 'audio/en/J-objibwe.mp3',
      '11': 'audio/en/K-octopus-pouch.mp3',
      '12': 'audio/en/L-comanche-blanket.mp3',
      '13': 'audio/en/M-knife_sheath.mp3',
      '14': 'audio/en/N-trade_beads.mp3',
      '15': 'audio/en/O-woodland-bag.mp3',
      '16': 'audio/en/PQS-handbags+shoes.mp3',
      '17': 'audio/en/PQS-handbags+shoes.mp3',
      '18': 'audio/en/R-Ida_Dress.mp3',
      '19': 'audio/en/PQS-handbags+shoes.mp3',
      '20': 'audio/en/T-eage-talon-necklace.mp3',
      '21': 'audio/en/U-plains-shirt.mp3',
      '22': 'audio/en/V-beaded-vest.mp3',
      '23': 'audio/en/W-moccasins.mp3',
      '24': 'audio/en/Y-african-except-ostrich.mp3',
      '25': 'audio/en/Y-african-except-ostrich.mp3',
      '26': 'audio/en/Z-ostrich-egg-necklace.mp3',
}

var nameDict_es = {
      '1': '',
      '2': '',
      '3': '',
      '4': '',
      '5': '',
      '6': '',
      '7': '',
      '8': '',
      '9': '',
      '10': '',
      '11': '',
      '12': '',
      '13': '',
      '14': '',
      '15': '',
      '16': '',
      '17': '',
      '18': '',
      '19': '',
      '20': '',
      '21': '',
      '22': '',
      '23': '',
      '24': '',
      '25': '',
      '26': '',
      'error': ''
    };

var captionDict_es = {
      '1': '',
      '2': '',
      '3': '',
      '4': '',
      '5': '',
      '6': '',
      '7': '',
      '8': '',
      '9': '',
      '10': '',
      '11': '',
      '12': '',
      '13': '',
      '14': '',
      '15': '',
      '16': '',
      '17': '',
      '18': '',
      '19': '',
      '20': '',
      '21': '',
      '22': '',
      '23': '',
      '24': '',
      '25': '',
      '26': '',
      'error': ''
}

var textDict_es = {
      '1': '',
      '2': '',
      '3': '',
      '4': '',
      '5': '',
      '6': '',
      '7': '',
      '8': '',
      '9': '',
      '10': '',
      '11': '',
      '12': '',
      '13': '',
      '14': '',
      '15': '',
      '16': '',
      '17': '',
      '18': '',
      '19': '',
      '20': '',
      '21': '',
      '22': '',
      '23': '',
      '24': '',
      '25': '',
      '26': '',
      'error': "Vaya, un artefacto con ese número no parece existir en esta galería. ¡Verifique que haya seleccionado la galería apropiada y luego intente con un número diferente!"
    };

var audioDict_es = {
      '1': '',
      '2': '',
      '3': '',
      '4': '',
      '5': '',
      '6': '',
      '7': '',
      '8': '',
      '9': '',
      '10': '',
      '11': '',
      '12': '',
      '13': '',
      '14': '',
      '15': '',
      '16': '',
      '17': '',
      '18': '',
      '19': '',
      '20': '',
      '21': '',
      '22': '',
      '23': '',
      '24': '',
      '25': '',
      '26': '',
}
